- name: install haproxy
  apt: name=haproxy state=present
  when:  ansible_os_family  == "Debian"
- name: Enable init script
  replace: dest='/etc/default/haproxy' regexp='ENABLED=0' replace='ENABLED=1'
  when:  ansible_os_family  == "Debian"
- name: Update HAProxy config
  template: src=haproxy.j2 dest=/etc/haproxy/haproxy.cfg backup=yes
  notify: 
    - restart haproxy
- name: haproxy service running and enabled
  service: name=haproxy enabled=yes
