---
#- name: Timezone
#  timezone: name=Europe/Madrid
- name: Check if ntp is installed and updated
  yum: name=ntp state=latest
  when: ansible_os_family == "RedHat"
- name: Check if ntp is installed and updated
  apt: name=ntp state=latest
  when: ansible_os_family == "Debian"
- name: Configure the ntp daemon with a template
  template: src=ntp.j2 dest=/etc/ntp.conf
  notify: 
      - NTP restart
