---
- name: Update-software on node
  yum: name=* state=latest update_cache=yes
  when: ansible_os_family == "RedHat"

- name: update apt cache
  apt: update_cache=yes 
  when: ansible_os_family == "Debian"

- name: Update all packages on node
  apt:  upgrade=dist
  when: ansible_os_family == "Debian"
